apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "default" # Ensure it matches your StorageClass name
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
