apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
  labels:
    type: my-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # Added missing field
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /exports
    server: 192.168.0.1
