apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    Kubernetes.io/cluster-service: "true"
provisioner: k8s.io/azure-disk # for Microsoft Azure. Change as needed

