apiVersion: v1
kind: Pod
metadata:
  name: kuard-tls
spec:
  containers:
    - name: kuard-tls
      image: gcr.io/kuar-demo/kuard-amd64:blue
      imagePullPolicy: Always
      volumeMounts: # 1️⃣ Mount a volume into the container
        - name: tls-certs
          mountPath: "/tls" # Inside the container, files will appear under /tls
          readOnly: true
  volumes:
    - name: tls-certs # 2️⃣ Define the volume at Pod level
      secret: # The volume comes from a Kubernetes Secret
        secretName: kuard-tls # Must match an existing Secret
